import { useState } from 'react'
import { motion } from 'framer-motion'

export default function ReferralHub() {
  const [copied, setCopied] = useState(false)
  const refLink = "https://zyrox.io/ref/0x4F9...A1B2"

  const handleCopy = () => {
    navigator.clipboard.writeText(refLink)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="os-view-container">
      
      <div className="ref-header">
        <h2 className="sys-title">NETWORK <span style={{ color: 'var(--neon-green)' }}>EXPANSION</span></h2>
        <p className="sys-desc">Invite operators to the ZyroX ecosystem to earn passive XP yield.</p>
      </div>

      <div className="ref-grid">
        
        {/* Link Panel */}
        <div className="os-panel link-panel">
          <h3>YOUR REFERRAL UPLINK</h3>
          <p>Share this cryptographic link. You earn 10% of the XP generated by invited operators.</p>
          
          <div className="link-box">
            <input type="text" readOnly value={refLink} className="ref-input" />
            <button className={`cyber-btn sm ${copied ? 'success' : ''}`} onClick={handleCopy}>
              {copied ? 'COPIED ✓' : 'COPY LINK'}
            </button>
          </div>
        </div>

        {/* Stats Panel */}
        <div className="os-panel stats-panel">
          <div className="ref-stat">
            <span className="label">ACTIVE RECRUITS</span>
            <span className="val">24</span>
          </div>
          <div className="ref-stat">
            <span className="label">TOTAL XP EARNED</span>
            <span className="val" style={{ color: 'var(--neon-purple)' }}>8,450</span>
          </div>
          <div className="ref-stat">
            <span className="label">TIER</span>
            <span className="val" style={{ color: 'var(--neon-cyan)', fontSize: '1rem' }}>ELITE RECRUITER</span>
          </div>
        </div>

        {/* Recent Invites List */}
        <div className="os-panel list-panel">
          <h3 className="list-title">RECENT PROTOCOL JOINS</h3>
          <table className="ref-table">
            <thead>
              <tr>
                <th>WALLET ID</th>
                <th>JOIN DATE</th>
                <th>XP GENERATED (10%)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>0x8A2...3C9F</td>
                <td>2026-04-18</td>
                <td style={{ color: 'var(--neon-purple)' }}>+ 450 XP</td>
              </tr>
              <tr>
                <td>0x1B4...7D2E</td>
                <td>2026-04-16</td>
                <td style={{ color: 'var(--neon-purple)' }}>+ 120 XP</td>
              </tr>
              <tr>
                <td>0x9F1...4A5B</td>
                <td>2026-04-12</td>
                <td style={{ color: 'var(--neon-purple)' }}>+ 890 XP</td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>

      <style>{`
        .os-view-container { display: flex; flex-direction: column; height: 100%; max-width: 1000px; margin: 0 auto; }
        
        .ref-header { margin-bottom: 40px; }
        .sys-desc { color: var(--text-dim); }

        .ref-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 24px; padding-bottom: 40px; }
        
        .link-panel { grid-column: 1 / 2; display: flex; flex-direction: column; justify-content: center; }
        .link-panel h3 { font-size: 1.2rem; color: #fff; margin-bottom: 8px; }
        .link-panel p { color: var(--text-dim); font-size: 0.9rem; margin-bottom: 24px; }
        
        .link-box { display: flex; gap: 12px; }
        .ref-input { flex: 1; background: rgba(0,0,0,0.5); border: 1px solid var(--panel-border); color: var(--neon-cyan); padding: 12px 16px; font-family: var(--font-mono); border-radius: var(--radius-sm); outline: none; }
        .cyber-btn.success { border-color: var(--neon-green); color: var(--neon-green); }

        .stats-panel { grid-column: 2 / 3; display: flex; flex-direction: column; gap: 24px; justify-content: center; }
        .ref-stat { display: flex; flex-direction: column; gap: 4px; border-bottom: 1px dashed rgba(255,255,255,0.1); padding-bottom: 12px; }
        .ref-stat:last-of-type { border-bottom: none; padding-bottom: 0; }
        .ref-stat .label { font-family: var(--font-mono); font-size: 0.7rem; color: var(--text-muted); }
        .ref-stat .val { font-family: var(--font-display); font-size: 1.8rem; font-weight: bold; color: #fff; }

        .list-panel { grid-column: 1 / -1; }
        .list-title { font-size: 1rem; color: var(--text-dim); margin-bottom: 16px; letter-spacing: 1px; }
        
        .ref-table { width: 100%; border-collapse: collapse; text-align: left; font-family: var(--font-mono); font-size: 0.85rem; }
        .ref-table th { color: var(--text-muted); padding: 12px; border-bottom: 1px solid rgba(255,255,255,0.1); font-weight: normal; }
        .ref-table td { color: var(--text-main); padding: 16px 12px; border-bottom: 1px dashed rgba(255,255,255,0.05); }

        @media (max-width: 768px) {
          .ref-grid { grid-template-columns: 1fr; }
          .stats-panel { grid-column: 1 / -1; flex-direction: row; flex-wrap: wrap; }
          .ref-stat { flex: 1; min-width: 120px; border-bottom: none; border-right: 1px dashed rgba(255,255,255,0.1); }
          .ref-stat:last-of-type { border-right: none; }
          .link-box { flex-direction: column; }
        }
      `}</style>
    </div>
  )
}
